#!/usr/bin/env bash
# Generated by scripts/generate-install-script.ts; do not edit.
main() {
set -Eeuo pipefail
YES=0 CHECK=0 DEPENDENCIES_ONLY=0 TMP=''
PORTEAU_VERSION='0.1.0-alpha.2'
PORTEAU_REGISTRY='https://registry.npmjs.org'
PORTEAU_PREFIX="${HOME:-}/.local"
PORTEAU_BIN="$PORTEAU_PREFIX/bin/porteau"
cleanup() { if [[ -n "$TMP" ]]; then rm -rf -- "$TMP"; fi; }
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT TERM
usage() { printf '%s\n' 'Usage: ./install.sh [--check] [--yes] [--dependencies-only] [--help]' '  --dependencies-only  Check/install Node and native tools, but not Porteau'; }
while (( $# )); do
  case "$1" in --check) CHECK=1 ;; --yes) YES=1 ;; --dependencies-only) DEPENDENCIES_ONLY=1 ;; --help|-h) usage; exit 0 ;; *) usage >&2; exit 2 ;; esac
  shift
done
(( CHECK && YES )) && { echo '--check and --yes cannot be used together.' >&2; exit 2; }
[[ -r /etc/os-release ]] || { echo 'Unsupported system: missing /etc/os-release' >&2; exit 1; }
# shellcheck disable=SC1091
. /etc/os-release
[[ "${ID:-}" == ubuntu ]] || { echo 'Automatic setup supports Ubuntu only.' >&2; exit 1; }
ARCH="$(dpkg --print-architecture)"; ASSET='' URL='' SIZE='' SHA=''
case "${VERSION_ID:-}/${VERSION_CODENAME:-}/$ARCH" in
  "22.04/jammy/amd64") ASSET='mydumper_1.0.3-1.jammy_amd64.deb'; URL='https://github.com/mydumper/mydumper/releases/download/v1.0.3-1/mydumper_1.0.3-1.jammy_amd64.deb'; SIZE='1627788'; SHA='9f7fb46c03e1a721e86d71c42a3fe3bd88f1a7b0ec80fa91c7736826f7f1e6f4' ;;
  "24.04/noble/amd64") ASSET='mydumper_1.0.3-1.noble_amd64.deb'; URL='https://github.com/mydumper/mydumper/releases/download/v1.0.3-1/mydumper_1.0.3-1.noble_amd64.deb'; SIZE='9624536'; SHA='824c3c78e9bd5311a906a383d7596ff70363e32413df44fe7c58fd8914e5445b' ;;
  "24.04/noble/arm64") ASSET='mydumper_1.0.3-1.noble_arm64.deb'; URL='https://github.com/mydumper/mydumper/releases/download/v1.0.3-1/mydumper_1.0.3-1.noble_arm64.deb'; SIZE='1609756'; SHA='7b6585df47316e375fee88c115ddbad1d876004fc57a860b6949acbef5a393d6' ;;
  *) echo 'Supported targets: Ubuntu 22.04 amd64; Ubuntu 24.04 amd64; Ubuntu 24.04 arm64.' >&2; exit 1 ;;
esac
tool_version() { local v; command -v "$1" >/dev/null 2>&1 || return 1; v="$($1 --version 2>&1)"; [[ "$v" =~ ^$1\ v([0-9]+\.[0-9]+\.[0-9]+-[0-9]+),\ built\ against\ [^$'\r\n']+(\ with\ SSL\ support)?$ ]] || return 1; printf '%s' "${BASH_REMATCH[1]}"; }
version_at_least() { [[ -n "$1" ]] && dpkg --compare-versions "$1" ge "$2"; }
machine_ok() { local help; help="$("$1" --help 2>&1)" && [[ "$help" == *--machine-log-json* ]]; }
tool_pair_ok() { version_at_least "$1" '1.0.3-1' && version_at_least "$2" '1.0.3-1' && [[ "$1" == "$2" ]] && machine_ok mydumper && machine_ok myloader; }
node_ok() { local npm_version; command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1 && node -e 'const a=process.versions.node.split(".").map(Number),m="22.18.0".split(".").map(Number);process.exit(a[0]>m[0]||(a[0]===m[0]&&(a[1]>m[1]||(a[1]===m[1]&&a[2]>=m[2])))?0:1)' && npm_version="$(npm --version 2>/dev/null)" && [[ "$npm_version" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]] ; }
porteau_ok() {
  local package="$PORTEAU_PREFIX/lib/node_modules/porteau/package.json" expected launcher
  [[ -f "$package" && ! -L "$package" && -x "$PORTEAU_BIN" ]] || return 1
  [[ "$(node -e 'const p=require(process.argv[1]);process.stdout.write(p.name+"@"+p.version+" "+p.bin.porteau)' "$package" 2>/dev/null)" == "porteau@$PORTEAU_VERSION dist/cli.mjs" ]] || return 1
  expected="$(readlink -f "$PORTEAU_PREFIX/lib/node_modules/porteau/dist/cli.mjs")"
  launcher="$(readlink -f "$PORTEAU_BIN")"
  [[ -n "$expected" && "$launcher" == "$expected" && "$("$PORTEAU_BIN" --version 2>/dev/null)" == "$PORTEAU_VERSION" ]]
}
validate_user_prefix() {
  [[ -n "${HOME:-}" && "$HOME" == /* && "$HOME" != / && "$HOME" != *$'\n'* ]] || { echo 'HOME must be a sane absolute path for a user-owned Porteau installation.' >&2; return 1; }
  (( EUID != 0 )) || { echo 'Run as your normal user; the installer invokes sudo only for disclosed system packages.' >&2; return 1; }
  local path owner
  for path in "$HOME" "$PORTEAU_PREFIX"; do
    [[ -e "$path" || -L "$path" ]] || continue
    [[ -d "$path" && ! -L "$path" ]] || { echo "$path must be an existing real directory." >&2; return 1; }
    owner="$(stat -c %u "$path")"; [[ "$owner" == "$EUID" ]] || { echo "$path must be owned by the current user." >&2; return 1; }
    [[ -w "$path" && -x "$path" ]] || { echo "$path must be writable by the current user." >&2; return 1; }
  done
}
verify_release() {
  case ":$PATH:" in *":$PORTEAU_PREFIX/bin:"*) ;; *) echo "Add Porteau to this shell with: export PATH=\"$PORTEAU_PREFIX/bin:\$PATH\"" ;; esac
  porteau_ok || { echo 'Porteau package or launcher verification failed.' >&2; return 1; }
  [[ -n "$TMP" ]] || TMP="$(mktemp -d)"
  (cd "$TMP" && env -u PORTEAU_MYDUMPER -u PORTEAU_MYLOADER "$PORTEAU_BIN" doctor --no-interactive >/dev/null) || { echo 'Porteau doctor verification failed.' >&2; return 1; }
}
(( ! DEPENDENCIES_ONLY && ! CHECK )) && validate_user_prefix
NODE=0 TOOLS=0 PORTEAU=0; node_ok || NODE=1
MYDUMPER_VERSION="$(tool_version mydumper || true)"
MYLOADER_VERSION="$(tool_version myloader || true)"
tool_pair_ok "$MYDUMPER_VERSION" "$MYLOADER_VERSION" || TOOLS=1
(( ! DEPENDENCIES_ONLY )) && { porteau_ok || PORTEAU=1; }
BLOCKED_DOWNGRADE=0
if (( TOOLS )) && { { [[ -n "$MYDUMPER_VERSION" ]] && dpkg --compare-versions "$MYDUMPER_VERSION" gt '1.0.3-1'; } || { [[ -n "$MYLOADER_VERSION" ]] && dpkg --compare-versions "$MYLOADER_VERSION" gt '1.0.3-1'; }; }; then BLOCKED_DOWNGRADE=1; fi
echo 'Porteau installation plan'
if (( NODE )); then
  echo '  Node.js target: 24 from the third-party NodeSource repository'
  echo '  Signing key: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key'
  echo '  Required fingerprint: 6F71F525282841EEDAF851B42F59B5F99B1BE0B4'
  echo '  Repository: deb [signed-by=/usr/share/keyrings/porteau-nodesource.gpg] https://deb.nodesource.com/node_24.x nodistro main'
  echo '  sudo install -m 0644 <verified-keyring> /usr/share/keyrings/porteau-nodesource.gpg'
  echo '  sudo install -m 0644 <verified-source-list> /etc/apt/sources.list.d/porteau-nodesource.list'
  echo '  sudo apt-get update'
  echo '  Validate with: apt-cache madison nodejs (require NodeSource node_24.x and major 24)'
  echo '  sudo env DEBIAN_FRONTEND=noninteractive apt-get install --yes nodejs=<validated NodeSource 24 candidate>'
fi
if (( TOOLS )); then
  echo "  Native package: $URL"
  echo "  Required size: $SIZE; required SHA-256: $SHA"
  echo "  sudo env DEBIAN_FRONTEND=noninteractive apt-get install --yes ./$ASSET (from the verified temporary directory)"
fi
if (( PORTEAU )); then
  echo "  CLI package: porteau@$PORTEAU_VERSION from $PORTEAU_REGISTRY"
  echo "  npm view --registry $PORTEAU_REGISTRY --userconfig <temporary>/npmrc --cache <temporary>/npm-cache --json porteau@$PORTEAU_VERSION version"
  echo "  npm install --global --prefix $PORTEAU_PREFIX --ignore-scripts --no-audit --no-fund --registry $PORTEAU_REGISTRY --userconfig <temporary>/npmrc --cache <temporary>/npm-cache porteau@$PORTEAU_VERSION"
  echo '  npm uses temporary cache/config and never sudo; sudo is limited to the APT/keyring commands above.'
elif (( DEPENDENCIES_ONLY )); then
  echo '  Dependencies-only: Porteau will not be checked or installed'
fi
for marker in NVM_DIR ASDF_DIR MISE_DATA_DIR VOLTA_HOME; do [[ -n "${!marker:-}" ]] && echo "  Warning: user-managed Node detected ($marker); system Node will not replace its shims."; done
(( BLOCKED_DOWNGRADE )) && { echo "Automatic setup will not downgrade detected native tools ($MYDUMPER_VERSION / $MYLOADER_VERSION) to 1.0.3-1; install a matching supported pair manually." >&2; exit 1; }
if (( ! NODE && ! TOOLS && DEPENDENCIES_ONLY )); then
  echo 'All dependencies are compatible.'; exit 0
fi
if (( ! NODE && ! TOOLS && ! PORTEAU )); then
  verify_release || exit 1
  echo "Porteau $PORTEAU_VERSION and all dependencies are ready."
  exit 0
fi
(( CHECK )) && { echo 'Check only: no changes made.'; exit 1; }
if (( ! YES )); then
  { : </dev/tty && : >/dev/tty; } 2>/dev/null || { echo 'No TTY: refusing mutation without --yes.' >&2; exit 1; }
  printf 'Proceed? [y/N] ' >/dev/tty; read -r answer </dev/tty || true
  [[ "$answer" == y || "$answer" == Y ]] || { echo 'Cancelled; install dependencies manually or rerun with --yes.'; exit 0; }
fi
TMP="$(mktemp -d)"
mkdir -m 0700 "$TMP/npm-cache"
printf 'ignore-scripts=true\n' >"$TMP/npmrc"
if (( TOOLS )); then
  curl --proto '=https' --proto-redir '=https' --fail --location --silent --show-error "$URL" --output "$TMP/$ASSET"
  [[ "$(stat -c %s "$TMP/$ASSET")" == "$SIZE" ]] || { echo 'Package size mismatch.' >&2; exit 1; }
  echo "$SHA  $TMP/$ASSET" | sha256sum --check --status || { echo 'Package checksum mismatch.' >&2; exit 1; }
fi
if (( NODE )); then
  command -v gpg >/dev/null 2>&1 || { echo 'gpg is required to verify the NodeSource signing key; install gnupg manually.' >&2; exit 1; }
  curl --proto '=https' --proto-redir '=https' --fail --location --silent --show-error 'https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key' --output "$TMP/nodesource.asc"
  KEY_INFO="$(gpg --batch --show-keys --with-colons "$TMP/nodesource.asc")"
  KEY_FINGERPRINTS="$(awk -F: '$1=="pub"{primary=1;next} $1=="sub"{primary=0;next} $1=="fpr"&&primary{print $10;primary=0}' <<<"$KEY_INFO")"
  [[ "$KEY_FINGERPRINTS" == '6F71F525282841EEDAF851B42F59B5F99B1BE0B4' ]] || { echo 'NodeSource key fingerprint mismatch.' >&2; exit 1; }
  gpg --batch --dearmor --output "$TMP/nodesource.gpg" "$TMP/nodesource.asc"
  KEYRING_INFO="$(gpg --batch --show-keys --with-colons "$TMP/nodesource.gpg")"
  KEYRING_FINGERPRINTS="$(awk -F: '$1=="pub"{primary=1;next} $1=="sub"{primary=0;next} $1=="fpr"&&primary{print $10;primary=0}' <<<"$KEYRING_INFO")"
  [[ "$KEYRING_FINGERPRINTS" == '6F71F525282841EEDAF851B42F59B5F99B1BE0B4' ]] || { echo 'Generated NodeSource keyring fingerprint mismatch.' >&2; exit 1; }
  printf '%s\n' 'deb [signed-by=/usr/share/keyrings/porteau-nodesource.gpg] https://deb.nodesource.com/node_24.x nodistro main' >"$TMP/nodesource.list"
  sudo install -m 0644 "$TMP/nodesource.gpg" '/usr/share/keyrings/porteau-nodesource.gpg'
  sudo install -m 0644 "$TMP/nodesource.list" '/etc/apt/sources.list.d/porteau-nodesource.list'
  sudo apt-get update
  CANDIDATE="$(apt-cache madison nodejs | awk -F'|' '{for(i=1;i<=3;i++)gsub(/^[[:space:]]+|[[:space:]]+$/, "", $i)} $1=="nodejs" && $2 ~ /^24\./ && index($3,"https://deb.nodesource.com/node_24.x")==1 {print $2; exit}')"
  [[ -n "$CANDIDATE" ]] || { echo 'NodeSource did not provide a Node.js 24 candidate.' >&2; exit 1; }
  sudo env DEBIAN_FRONTEND=noninteractive apt-get install --yes "nodejs=$CANDIDATE"
fi
if (( PORTEAU )); then
  PUBLISHED_VERSION="$(npm view --registry "$PORTEAU_REGISTRY" --userconfig "$TMP/npmrc" --cache "$TMP/npm-cache" --json "porteau@$PORTEAU_VERSION" version 2>/dev/null | tr -d '"[:space:]')"
  [[ "$PUBLISHED_VERSION" == "$PORTEAU_VERSION" ]] || { echo "porteau@$PORTEAU_VERSION is not available from the expected registry." >&2; exit 1; }
fi
(( TOOLS )) && (cd "$TMP" && sudo env DEBIAN_FRONTEND=noninteractive apt-get install --yes "./$ASSET")
if (( PORTEAU )); then
  npm install --global --prefix "$PORTEAU_PREFIX" --ignore-scripts --no-audit --no-fund --registry "$PORTEAU_REGISTRY" --userconfig "$TMP/npmrc" --cache "$TMP/npm-cache" "porteau@$PORTEAU_VERSION"
fi
MYDUMPER_VERSION="$(tool_version mydumper || true)"
MYLOADER_VERSION="$(tool_version myloader || true)"
if ! node_ok || ! tool_pair_ok "$MYDUMPER_VERSION" "$MYLOADER_VERSION"; then
  echo 'Post-install dependency verification failed.' >&2
  exit 1
fi
if (( ! DEPENDENCIES_ONLY )); then
  verify_release || exit 1
  echo "Porteau $PORTEAU_VERSION and all dependencies installed and verified."
else
  echo 'Dependencies installed and verified.'
fi
}
{ main "$@"; }
