import { readFileSync } from 'node:fs'
import { writeFile } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import packageJson from '../package.json' with { type: 'json' }
import { compatibilityManifest } from '../src/setup/manifest.js'
import {
  minimumNodeVersion,
  nodeSourceFingerprint,
  nodeSourceKeyring,
  nodeSourceKeyUrl,
  nodeSourceList,
  nodeSourceRepository,
  nodeTargetMajor,
  supportedTargetDescription,
} from '../src/setup/policy.js'

const TEMPLATE_PATH = fileURLToPath(new URL('./install.sh.template', import.meta.url))
const PORTEAU_REGISTRY = 'https://registry.npmjs.org'
const LEFTOVER_TOKEN = /@[A-Z][A-Z0-9_]*@/u

const INSTALL_SCRIPT_TOKEN_KEYS = [
  'PORTEAU_VERSION',
  'PORTEAU_RELEASED',
  'PORTEAU_REGISTRY',
  'ASSET_CASES',
  'SUPPORTED_TARGET_DESCRIPTION',
  'MYDUMPER_MINIMUM_VERSION',
  'MYLOADER_MINIMUM_VERSION',
  'ENGINE_VERSION',
  'MINIMUM_NODE_VERSION',
  'NODE_TARGET_MAJOR',
  'NODE_SOURCE_KEY_URL',
  'NODE_SOURCE_FINGERPRINT',
  'NODE_SOURCE_KEYRING',
  'NODE_SOURCE_LIST',
  'NODE_SOURCE_REPOSITORY',
] as const

type InstallScriptToken = (typeof INSTALL_SCRIPT_TOKEN_KEYS)[number]

type InstallScriptSubstitutions = { readonly [K in InstallScriptToken]: string }

function buildInstallScriptSubstitutions(packageVersion: string): InstallScriptSubstitutions {
  const assetCases = compatibilityManifest.assets
    .map(
      (asset) =>
        `  "${asset.ubuntu}/${asset.codename}/${asset.architecture}") ASSET='${asset.filename}'; URL='${asset.url}'; SIZE='${asset.size}'; SHA='${asset.sha256}' ;;`,
    )
    .join('\n')

  return {
    PORTEAU_VERSION: packageVersion,
    PORTEAU_RELEASED: packageVersion !== '0.0.0' ? '1' : '0',
    PORTEAU_REGISTRY,
    ASSET_CASES: assetCases,
    SUPPORTED_TARGET_DESCRIPTION: supportedTargetDescription,
    MYDUMPER_MINIMUM_VERSION: compatibilityManifest.engine.tools.mydumper.minimumVersion,
    MYLOADER_MINIMUM_VERSION: compatibilityManifest.engine.tools.myloader.minimumVersion,
    ENGINE_VERSION: compatibilityManifest.engine.version,
    MINIMUM_NODE_VERSION: minimumNodeVersion,
    NODE_TARGET_MAJOR: String(nodeTargetMajor),
    NODE_SOURCE_KEY_URL: nodeSourceKeyUrl,
    NODE_SOURCE_FINGERPRINT: nodeSourceFingerprint,
    NODE_SOURCE_KEYRING: nodeSourceKeyring,
    NODE_SOURCE_LIST: nodeSourceList,
    NODE_SOURCE_REPOSITORY: nodeSourceRepository,
  }
}

function applyInstallScriptSubstitutions(
  template: string,
  substitutions: InstallScriptSubstitutions,
): string {
  let out = template
  for (const key of INSTALL_SCRIPT_TOKEN_KEYS) {
    const needle = key === 'ASSET_CASES' ? `# @${key}@` : `@${key}@`
    const parts = out.split(needle)
    if (parts.length < 2) throw new Error(`Install template missing token ${needle}`)
    out = parts.join(substitutions[key])
  }
  if (LEFTOVER_TOKEN.test(out))
    throw new Error(
      `Unsubstituted install template token(s): ${out.match(LEFTOVER_TOKEN)?.join(', ')}`,
    )
  return out
}

export function renderInstallScript(packageVersion = packageJson.version): string {
  if (!/^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/u.test(packageVersion))
    throw new Error('Package version is unsafe to embed in install.sh')

  const template = readFileSync(TEMPLATE_PATH, 'utf8')
  const substitutions = buildInstallScriptSubstitutions(packageVersion)
  // Template-only: SC2317 from the lone *) arm before # @ASSET_CASES@ is filled in.
  return applyInstallScriptSubstitutions(template, substitutions).replace(
    /^# shellcheck disable=SC2317$/mu,
    '# Generated by scripts/generate-install-script.ts; do not edit.',
  )
}

if (import.meta.main)
  await writeFile(process.argv[2] ?? 'install.sh', renderInstallScript(process.argv[3]), {
    mode: 0o755,
  })
