import { writeFile } from 'node:fs/promises'
import { compatibilityManifest } from '../src/setup/manifest.js'
import {
  minimumNodeVersion,
  nodeSourceFingerprint,
  nodeSourceKeyring,
  nodeSourceKeyUrl,
  nodeSourceList,
  nodeSourceRepository,
  nodeTargetMajor,
  supportedTargetDescription,
} from '../src/setup/policy.js'

export function renderInstallScript(): string {
  const cases = compatibilityManifest.assets
    .map(
      (asset) =>
        `  "${asset.ubuntu}/${asset.codename}/${asset.architecture}") ASSET='${asset.filename}'; URL='${asset.url}'; SIZE='${asset.size}'; SHA='${asset.sha256}' ;;`,
    )
    .join('\n')
  return `#!/usr/bin/env bash
# Generated by scripts/generate-install-script.ts; do not edit.
set -Eeuo pipefail
YES=0 CHECK=0 TMP=''
cleanup() { if [[ -n "$TMP" ]]; then rm -rf -- "$TMP"; fi; }
trap cleanup EXIT
trap 'exit 129' HUP
trap 'exit 130' INT TERM
usage() { printf '%s\\n' 'Usage: ./install.sh [--check|--yes|--help]'; }
while (( $# )); do
  case "$1" in --check) CHECK=1 ;; --yes) YES=1 ;; --help|-h) usage; exit 0 ;; *) usage >&2; exit 2 ;; esac
  shift
done
(( CHECK && YES )) && { echo '--check and --yes cannot be used together.' >&2; exit 2; }
[[ -r /etc/os-release ]] || { echo 'Unsupported system: missing /etc/os-release' >&2; exit 1; }
# shellcheck disable=SC1091
. /etc/os-release
[[ "\${ID:-}" == ubuntu ]] || { echo 'Automatic setup supports Ubuntu only.' >&2; exit 1; }
ARCH="$(dpkg --print-architecture)"; ASSET='' URL='' SIZE='' SHA=''
case "\${VERSION_ID:-}/\${VERSION_CODENAME:-}/$ARCH" in
${cases}
  *) echo 'Supported targets: ${supportedTargetDescription}.' >&2; exit 1 ;;
esac
tool_version() { local v; command -v "$1" >/dev/null 2>&1 || return 1; v="$($1 --version 2>&1)"; [[ "$v" =~ ^$1\\ v([0-9]+\\.[0-9]+\\.[0-9]+-[0-9]+),\\ built\\ against\\ [^$'\\r\\n']+(\\ with\\ SSL\\ support)?$ ]] || return 1; printf '%s' "\${BASH_REMATCH[1]}"; }
version_at_least() { [[ -n "$1" ]] && dpkg --compare-versions "$1" ge "$2"; }
machine_ok() { local help; help="$("$1" --help 2>&1)" && [[ "$help" == *--machine-log-json* ]]; }
tool_pair_ok() { version_at_least "$1" '${compatibilityManifest.engine.tools.mydumper.minimumVersion}' && version_at_least "$2" '${compatibilityManifest.engine.tools.myloader.minimumVersion}' && [[ "$1" == "$2" ]] && machine_ok mydumper && machine_ok myloader; }
node_ok() { local npm_version; command -v node >/dev/null 2>&1 && command -v npm >/dev/null 2>&1 && node -e 'const a=process.versions.node.split(".").map(Number),m="${minimumNodeVersion}".split(".").map(Number);process.exit(a[0]>m[0]||(a[0]===m[0]&&(a[1]>m[1]||(a[1]===m[1]&&a[2]>=m[2])))?0:1)' && npm_version="$(npm --version 2>/dev/null)" && [[ "$npm_version" =~ ^[0-9]+\\.[0-9]+\\.[0-9]+$ ]] ; }
NODE=0 TOOLS=0; node_ok || NODE=1
MYDUMPER_VERSION="$(tool_version mydumper || true)"
MYLOADER_VERSION="$(tool_version myloader || true)"
tool_pair_ok "$MYDUMPER_VERSION" "$MYLOADER_VERSION" || TOOLS=1
BLOCKED_DOWNGRADE=0
if (( TOOLS )) && { { [[ -n "$MYDUMPER_VERSION" ]] && dpkg --compare-versions "$MYDUMPER_VERSION" gt '${compatibilityManifest.engine.version}'; } || { [[ -n "$MYLOADER_VERSION" ]] && dpkg --compare-versions "$MYLOADER_VERSION" gt '${compatibilityManifest.engine.version}'; }; }; then BLOCKED_DOWNGRADE=1; fi
echo 'Porteau Ubuntu dependency plan'
if (( NODE )); then
  echo '  Node.js target: ${nodeTargetMajor} from the third-party NodeSource repository'
  echo '  Signing key: ${nodeSourceKeyUrl}'
  echo '  Required fingerprint: ${nodeSourceFingerprint}'
  echo '  Repository: ${nodeSourceRepository}'
  echo '  sudo install -m 0644 <verified-keyring> ${nodeSourceKeyring}'
  echo '  sudo install -m 0644 <verified-source-list> ${nodeSourceList}'
  echo '  sudo apt-get update'
  echo '  Validate with: apt-cache madison nodejs (require NodeSource node_${nodeTargetMajor}.x and major ${nodeTargetMajor})'
  echo '  sudo env DEBIAN_FRONTEND=noninteractive apt-get install --yes nodejs=<validated NodeSource ${nodeTargetMajor} candidate>'
fi
if (( TOOLS )); then
  echo "  Native package: $URL"
  echo "  Required size: $SIZE; required SHA-256: $SHA"
  echo "  sudo env DEBIAN_FRONTEND=noninteractive apt-get install --yes ./$ASSET (from the verified temporary directory)"
fi
for marker in NVM_DIR ASDF_DIR MISE_DATA_DIR VOLTA_HOME; do [[ -n "\${!marker:-}" ]] && echo "  Warning: user-managed Node detected ($marker); system Node will not replace its shims."; done
(( BLOCKED_DOWNGRADE )) && { echo "Automatic setup will not downgrade detected native tools ($MYDUMPER_VERSION / $MYLOADER_VERSION) to ${compatibilityManifest.engine.version}; install a matching supported pair manually." >&2; exit 1; }
(( NODE || TOOLS )) || { echo 'All dependencies are compatible.'; exit 0; }
(( CHECK )) && { echo 'Check only: no changes made.'; exit 1; }
if (( ! YES )); then
  { : </dev/tty && : >/dev/tty; } 2>/dev/null || { echo 'No TTY: refusing mutation without --yes.' >&2; exit 1; }
  printf 'Proceed? [y/N] ' >/dev/tty; read -r answer </dev/tty || true
  [[ "$answer" == y || "$answer" == Y ]] || { echo 'Cancelled; install dependencies manually or rerun with --yes.'; exit 0; }
fi
TMP="$(mktemp -d)"
if (( TOOLS )); then
  curl --proto '=https' --proto-redir '=https' --fail --location --silent --show-error "$URL" --output "$TMP/$ASSET"
  [[ "$(stat -c %s "$TMP/$ASSET")" == "$SIZE" ]] || { echo 'Package size mismatch.' >&2; exit 1; }
  echo "$SHA  $TMP/$ASSET" | sha256sum --check --status || { echo 'Package checksum mismatch.' >&2; exit 1; }
fi
if (( NODE )); then
  command -v gpg >/dev/null 2>&1 || { echo 'gpg is required to verify the NodeSource signing key; install gnupg manually.' >&2; exit 1; }
  curl --proto '=https' --proto-redir '=https' --fail --location --silent --show-error '${nodeSourceKeyUrl}' --output "$TMP/nodesource.asc"
  KEY_INFO="$(gpg --batch --show-keys --with-colons "$TMP/nodesource.asc")"
  KEY_FINGERPRINTS="$(awk -F: '$1=="pub"{primary=1;next} $1=="sub"{primary=0;next} $1=="fpr"&&primary{print $10;primary=0}' <<<"$KEY_INFO")"
  [[ "$KEY_FINGERPRINTS" == '${nodeSourceFingerprint}' ]] || { echo 'NodeSource key fingerprint mismatch.' >&2; exit 1; }
  gpg --batch --dearmor --output "$TMP/nodesource.gpg" "$TMP/nodesource.asc"
  KEYRING_INFO="$(gpg --batch --show-keys --with-colons "$TMP/nodesource.gpg")"
  KEYRING_FINGERPRINTS="$(awk -F: '$1=="pub"{primary=1;next} $1=="sub"{primary=0;next} $1=="fpr"&&primary{print $10;primary=0}' <<<"$KEYRING_INFO")"
  [[ "$KEYRING_FINGERPRINTS" == '${nodeSourceFingerprint}' ]] || { echo 'Generated NodeSource keyring fingerprint mismatch.' >&2; exit 1; }
  printf '%s\\n' '${nodeSourceRepository}' >"$TMP/nodesource.list"
  sudo install -m 0644 "$TMP/nodesource.gpg" '${nodeSourceKeyring}'
  sudo install -m 0644 "$TMP/nodesource.list" '${nodeSourceList}'
  sudo apt-get update
  CANDIDATE="$(apt-cache madison nodejs | awk -F'|' '{for(i=1;i<=3;i++)gsub(/^[[:space:]]+|[[:space:]]+$/, "", $i)} $1=="nodejs" && $2 ~ /^${nodeTargetMajor}\\./ && index($3,"https://deb.nodesource.com/node_${nodeTargetMajor}.x")==1 {print $2; exit}')"
  [[ -n "$CANDIDATE" ]] || { echo 'NodeSource did not provide a Node.js ${nodeTargetMajor} candidate.' >&2; exit 1; }
  sudo env DEBIAN_FRONTEND=noninteractive apt-get install --yes "nodejs=$CANDIDATE"
fi
(( TOOLS )) && (cd "$TMP" && sudo env DEBIAN_FRONTEND=noninteractive apt-get install --yes "./$ASSET")
MYDUMPER_VERSION="$(tool_version mydumper || true)"
MYLOADER_VERSION="$(tool_version myloader || true)"
if ! node_ok || ! tool_pair_ok "$MYDUMPER_VERSION" "$MYLOADER_VERSION"; then
  echo 'Post-install verification failed.' >&2
  exit 1
fi
echo 'Dependencies installed and verified.'
`
}

if (import.meta.main)
  await writeFile(process.argv[2] ?? 'install.sh', renderInstallScript(), { mode: 0o755 })
